### ISSUE TITLE
Pliers Hard to Add to Inventory

### ISSUE THREAD

**Issue by heather-fillerup-miller** [CS467-AI-Coder-Escape-Room/CS467-AI-Coder-Escape-Room#28]
**Describe the bug**
When opening the locked box, the pliers are hard to add to inventory. Have to click several times.

**To Reproduce**
1. Start Room
2. Once you solve the locked box, the pliers have to be clicked multiple times to add to inventory.

**Expected behavior**
Click on pliers and they are added

**Screenshots**

**Potential Fix**

**Comment by stevenzicka** [comment]
Fixed!
